### ISSUE TITLE
bug: due to non existing geometry when 

### ISSUE THREAD

**Issue by WolfgangISE** [DaveFoss/DAVE_core#3]
https://github.com/DaveFoss/DAVE_core/blob/0069d7a436b5b9acb425792cf5cad01abd0535ed/src/dave_core/io/file_io.py#L309

Traceback (most recent call last):
  File "C:\Users\wbiener\git\syn_grids_osm\examples\validation_scripts\import_dave_grids.py", line 42, in <module>
    el_network = create_pandapower(grid_data, opt_model=False, output_folder=dave_output_folder)
  File "C:\Users\wbiener\enviornments\dave\lib\site-packages\dave_core\converter\create_pandapower.py", line 657, in create_pandapower
    pp_to_json(net, file_path)
  File "C:\Users\wbiener\enviornments\dave\lib\site-packages\dave_core\io\file_io.py", line 309, in pp_to_json
    if not net.bus.empty and all(list(map(lambda x: isinstance(x, Point), net.bus.geometry))):
  File "C:\Users\wbiener\enviornments\dave\lib\site-packages\pandas\core\generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'geometry'

**Comment by tbanze** [comment]
query for geometry key added, so that geometry is only converted if it is present
